name: Publish release

on:
  push:
    tags:
    - 'v*' # Push events to matching *, i.e. 1.0, 20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      repository-projects: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build executable
      run: go build .

    - name: Tar executable
      run: tar -czvf flux-graph.linux-amd64.tar.gz flux-graph

    - name: Create release
      uses: ncipollo/release-action@v1
      id: create_release
      with:
        tag: ${{ github.ref_name }}
        draft: false
        prerelease: false
        artifacts: "flux-graph.linux-amd64.tar.gz"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
